### ISSUE TITLE
Configure ipv4 and ipv6 for the same interface.

### ISSUE THREAD

**Issue by ypid** [debops/ansible-ifupdown#16]
Hi

It seems that it is currently not possible to configure v4 and v6 for the same interface, correct?
The problem is that the v6 template is overwritten.

I tried:

    ifupdown_interfaces:
      - iface: 'eth0'
        inet6: 'static'
        options: |
          address fd03:dff9:8796:50f2::1
          netmask 64
      - iface: 'eth0'
        inet: 'static'
        options: |
          address 192.168.23.3
          netmask 24
          gateway 192.168.23.1

**Comment by drybjed** [comment]
You can use `item.filename` to create separate config files for IPv4 and IPv6. Here's an example: https://github.com/debops/ansible-ifupdown/blob/master/vars/example_static.yml

**Comment by ypid** [comment]
Right. That is one way :smile:
