### ISSUE TITLE
depending on the script

### ISSUE THREAD

**Issue by le9i0nx** [debops/ansible-ifupdown#27]
https://github.com/debops/ansible-ifupdown/blob/master/templates/usr/local/lib/ifupdown-reconfigure-interfaces.j2
I did not have on the target system logger and rsync
I think ansible must set (check), depending on the script.
Their absence leads to unforeseen behavior of a script.

Package: bsdutils , rsync

**Comment by drybjed** [comment]
Good idea. I'll add `rsync` to required packages and check if `logger` is available before using it.

**Comment by le9i0nx** [comment]
https://github.com/debops/ansible-ifupdown/pull/29
