### ISSUE TITLE
addresses does not properly parse prefix 32 and gives an error

### ISSUE THREAD

**Issue by ser** [debops/ansible-ifupdown#54]
If you set netmask with prefix 32 in your address, the role is not able to parse it

**Comment by ser** [comment]
The same with prefix 31, it parses it, but creates a shitty data in interfaces.d file

**Comment by drybjed** [comment]
@ser Does it work if you replace the `ipaddr` filter in `debops-playbooks` with the one from Ansible `devel` branch? The issue with `/31` prefix was recently resolved in `devel`, not sure about the `/32`.
